behaviors:
  PointAndShoot:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 3.0e-4
      beta: 7.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.5
        demo_path: Demos/AimShootMovilTar_0.demo
        learning_rate: 3e-4
        use_actions: false
        use_vail: false
    behavioral_cloning:
      strength: 0.5
      demo_path: Demos/AimShootMovilTar_0.demo
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 5000000
    time_horizon: 512
    summary_freq: 20000
    threaded: false